#!/usr/bin/env python3
# diegoHERNANDO 2023

import mouse 
import time

coordenadas = mouse.get_position()
aceptar = input("\nPress enter to start.\nYou have 3 seconds to place the mouse on the place you want.")
if (aceptar) != "":
    print("Pulsa Enter para empezar")
else:
    time.sleep(3)
    print(coordenadas)   
